spring:
  datasource:
    url: jdbc:mysql://localhost:3306/?useSSL=false
    username: root
    password: "p455w0rd"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: take-a-guide
springdoc:
  swagger-ui:
    path: "/api-docs"
server:
  port: 8081
