spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tag_orm?useSSL=false
    username: root
    password: "p455w0rd"
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: take-a-guide
springdoc:
  swagger-ui:
    path: "/api-docs"
server:
  port: 8081
