spring:
  datasource:
    url: jdbc:mysql://localhost:3306/take_a_guide
    username: root
    password: "p455w0rd"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: take-a-guide
springdoc:
  swagger-ui:
    path: "/api-docs"
server:
  port: 8081
